%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /home/kevin/catkin_workspace/src/arm_scan_controller/scan_dataV3

# camera intrinsics
# fr1
camera.fx: 537.0397155022208
camera.fy: 537.0397155022208
camera.cx: 640.5
camera.cy: 360.5
camera.width: 1280
camera.hight: 720

camera.tf2gazebo1: 0.0
camera.tf2gazebo2: 0.0
camera.tf2gazebo3: 1.0
camera.tf2gazebo4: -1.0
camera.tf2gazebo5: 0.0
camera.tf2gazebo6: 0.0
camera.tf2gazebo7: 0.0
camera.tf2gazebo8: -1.0
camera.tf2gazebo9: 0.0


# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
number_of_features: 500
scale_factor: 1.2
level_pyramid: 4
match_ratio: 2.0
max_num_lost: 10
min_inliers: 30
keyframe_rotation: 0.1
keyframe_translation: 0.1
map_point_erase_ratio: 0.1
